# Generated by Django 4.2.30 on 2026-09-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
    ]
